version: '3.5'
services:
  web_server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
    expose:
      - 80
    networks:
      - letschat
  app:
    environment:
      - DATABASE_URI=postgres://mtcawriaieekfa:878c2c19e6524a72342de8943973871d1c6a88b77ee5c84b34a83458124e75da@ec2-54-75-230-41.eu-west-1.compute.amazonaws.com:5432/db4jqtlpevbq8v
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9999:9999
    networks:
      - letschat
networks:
  letschat:
